package com.my.playground.composite;

public enum Designation {
    SALES_ASSOCIATE, SALES_MANAGER, UNKNOWN, Account_Executive, SENIOR_SALES_MANAGER, REGIONAL_HEAD, ASSISTANT_ENGINEER, ASSOCIATE_ENGINEER, ENGINEER_LEAD, ASSISTANT_SALES_ASSOCIATE
}
